//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voditel
{
    using System;
    using System.Collections.Generic;
    
    public partial class examiners
    {
        public string name { get; set; }
        public string lustname { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int id { get; set; }
    }
}
