//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voditel
{
    using System;
    using System.Collections.Generic;
    
    public partial class information_about_applicants
    {
        public int id { get; set; }
        public string lustname { get; set; }
        public string name { get; set; }
        public int databorn { get; set; }
        public string kategory { get; set; }
        public int dataex { get; set; }
        public int datetimeid { get; set; }
    
        public virtual DateTime DateTime { get; set; }
    }
}
